version: '3.9'
services:
  clientes_db:
    container_name: fastfood_db
    image: postgres:15
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fastfood_db
    ports:
      - "5432:5432"

volumes:
  postgres-data: